/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as ListPropertyRouteImport } from './routes/list-property'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesSlugRouteImport } from './routes/properties.$slug'
import { Route as PaymentsSuccessRouteImport } from './routes/payments.success'
import { Route as PaymentsFailureRouteImport } from './routes/payments.failure'
import { Route as AgentsSlugRouteImport } from './routes/agents.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ListPropertyRoute = ListPropertyRouteImport.update({
  id: '/list-property',
  path: '/list-property',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesSlugRoute = PropertiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PropertiesRoute,
} as any)
const PaymentsSuccessRoute = PaymentsSuccessRouteImport.update({
  id: '/payments/success',
  path: '/payments/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsFailureRoute = PaymentsFailureRouteImport.update({
  id: '/payments/failure',
  path: '/payments/failure',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsSlugRoute = AgentsSlugRouteImport.update({
  id: '/agents/$slug',
  path: '/agents/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/list-property': typeof ListPropertyRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/payments/failure': typeof PaymentsFailureRoute
  '/payments/success': typeof PaymentsSuccessRoute
  '/properties/$slug': typeof PropertiesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/list-property': typeof ListPropertyRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/payments/failure': typeof PaymentsFailureRoute
  '/payments/success': typeof PaymentsSuccessRoute
  '/properties/$slug': typeof PropertiesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/list-property': typeof ListPropertyRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/payments/failure': typeof PaymentsFailureRoute
  '/payments/success': typeof PaymentsSuccessRoute
  '/properties/$slug': typeof PropertiesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/list-property'
    | '/properties'
    | '/sitemap.xml'
    | '/admin'
    | '/agents/$slug'
    | '/payments/failure'
    | '/payments/success'
    | '/properties/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/list-property'
    | '/properties'
    | '/sitemap.xml'
    | '/admin'
    | '/agents/$slug'
    | '/payments/failure'
    | '/payments/success'
    | '/properties/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/list-property'
    | '/properties'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/agents/$slug'
    | '/payments/failure'
    | '/payments/success'
    | '/properties/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ListPropertyRoute: typeof ListPropertyRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AgentsSlugRoute: typeof AgentsSlugRoute
  PaymentsFailureRoute: typeof PaymentsFailureRoute
  PaymentsSuccessRoute: typeof PaymentsSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-property': {
      id: '/list-property'
      path: '/list-property'
      fullPath: '/list-property'
      preLoaderRoute: typeof ListPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$slug': {
      id: '/properties/$slug'
      path: '/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof PropertiesSlugRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/payments/success': {
      id: '/payments/success'
      path: '/payments/success'
      fullPath: '/payments/success'
      preLoaderRoute: typeof PaymentsSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/failure': {
      id: '/payments/failure'
      path: '/payments/failure'
      fullPath: '/payments/failure'
      preLoaderRoute: typeof PaymentsFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$slug': {
      id: '/agents/$slug'
      path: '/agents/$slug'
      fullPath: '/agents/$slug'
      preLoaderRoute: typeof AgentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PropertiesRouteChildren {
  PropertiesSlugRoute: typeof PropertiesSlugRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesSlugRoute: PropertiesSlugRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ListPropertyRoute: ListPropertyRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AgentsSlugRoute: AgentsSlugRoute,
  PaymentsFailureRoute: PaymentsFailureRoute,
  PaymentsSuccessRoute: PaymentsSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
